# Generated by Django 2.0.7 on 2018-07-05 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shufic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Coment')),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='Video_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 5, 19, 30, 34, 461448)),
        ),
        migrations.AddField(
            model_name='video',
            name='Video_like',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='video',
            name='Video_o',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='video',
            name='Video_title',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='Video_Url',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_video',
            field=models.ForeignKey(on_delete=True, to='shufic.Video'),
        ),
    ]
