# Generated by Django 2.0.7 on 2018-07-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shufic', '0002_auto_20180705_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='Video_data',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='video',
            name='Video_Url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='Video_like',
            field=models.IntegerField(default=0),
        ),
    ]
